sudo: required
language: rust
matrix:
  include:
  - rust: nightly
  - rust: beta
  - rust: stable

addons:
  apt:
    packages:
      - libudev-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

# load travis-cargo
before_script:
  - |
      export PATH=$HOME/.local/bin:$PATH &&
      cargo install cargo-travis

script:
  - |
      cargo build &&
      cargo test

after_success:
  - cargo coveralls
